import type { Catalog, State, TourStep } from "./api";

export const sampleState: State = {
  rail: "mock",
  network: null,
  agents: [
    {
      agent_id: "research-agent",
      description: "Checks new suppliers before a first order.",
      frozen: false,
      allowed_tools: ["company_lookup", "credit_report", "fx_rate", "fx_realtime", "news_search"],
      per_task_cap: "0.75",
      daily_cap: "25.00",
      approval_above: "0.25",
      spent_today: "0.05",
      current_task: { task_id: "playground-7f3a", spent: "0.05" },
      wallet_address: null,
      wallet_usdc: null,
    },
    {
      agent_id: "intern-agent",
      description: "Looks up exchange rates and news. Nothing else.",
      frozen: false,
      allowed_tools: ["fx_rate", "news_search"],
      per_task_cap: "0.20",
      daily_cap: "2.00",
      approval_above: "0.05",
      spent_today: "0.00",
      current_task: null,
      wallet_address: null,
      wallet_usdc: null,
    },
  ],
  approvals: [
    {
      id: "c8a44374fa68",
      created_at: "2026-10-01T09:42:01.232632+00:00",
      agent_id: "research-agent",
      task_id: "playground-7f3a",
      tool: "credit_report",
      item_name: "Credit report",
      vendor: "Credit Bureau (demo)",
      amount: "0.50",
      reason:
        "0.50 USD is above the 0.25 USD limit for automatic purchases, so a person has to approve it.",
      status: "pending",
    },
  ],
  events: [
    {
      id: "745f2d01c781",
      created_at: "2026-10-01T09:42:01.233548+00:00",
      agent_id: "research-agent",
      task_id: "playground-7f3a",
      tool: "credit_report",
      item_name: "Credit report",
      url: "http://127.0.0.1:8001/v1/credit-report",
      vendor: "Credit Bureau (demo)",
      amount: "0.50",
      decision: "hold",
      status: "held",
      reason_code: "needs_approval",
      reason:
        "0.50 USD is above the 0.25 USD limit for automatic purchases, so a person has to approve it.",
      tx: null,
      explorer_url: null,
    },
    {
      id: "636f195b78fc",
      created_at: "2026-10-01T09:42:01.228213+00:00",
      agent_id: "research-agent",
      task_id: "playground-7f3a",
      tool: null,
      item_name: null,
      url: "https://dossier-deals.example/full-dossier",
      vendor: null,
      amount: null,
      decision: "deny",
      status: "blocked",
      reason_code: "not_in_catalog",
      reason: "This seller isn't on the approved list, so nothing was paid.",
      tx: null,
      explorer_url: null,
    },
    {
      id: "d20ca0de35ba",
      created_at: "2026-10-01T09:42:01.218935+00:00",
      agent_id: "research-agent",
      task_id: "playground-7f3a",
      tool: "company_lookup",
      item_name: "Company record",
      url: "http://127.0.0.1:8001/v1/company",
      vendor: "Registry Data (demo)",
      amount: "0.05",
      decision: "allow",
      status: "settled",
      reason_code: "paid",
      reason: "Paid 0.05 USD to Registry Data (demo).",
      tx: "mock-02a1bbadc4e74189",
      explorer_url: null,
    },
  ],
};

export const sampleCatalog: Catalog = {
  items: [
    {
      tool: "company_lookup",
      name: "Company record",
      description: "Official registry entry for a company.",
      vendor: "Registry Data (demo)",
      price: "0.05",
    },
    {
      tool: "credit_report",
      name: "Credit report",
      description: "Payment history and credit score for a company.",
      vendor: "Credit Bureau (demo)",
      price: "0.50",
    },
    {
      tool: "fx_rate",
      name: "Exchange rate",
      description: "Daily rate between two currencies.",
      vendor: "FX Feed (demo)",
      price: "0.01",
    },
    {
      tool: "fx_realtime",
      name: "Live exchange rate",
      description: "Rate updated every second.",
      vendor: "FX Feed (demo)",
      price: "0.10",
    },
    {
      tool: "news_search",
      name: "News search",
      description: "Recent news about a company.",
      vendor: "News Index (demo)",
      price: "0.02",
    },
  ],
  agents: [
    {
      agent_id: "research-agent",
      description: "Checks new suppliers before a first order.",
      allowed_tools: ["company_lookup", "credit_report", "fx_rate", "fx_realtime", "news_search"],
      per_task_cap: "0.75",
      daily_cap: "25.00",
      approval_above: "0.25",
    },
    {
      agent_id: "intern-agent",
      description: "Looks up exchange rates and news. Nothing else.",
      allowed_tools: ["fx_rate", "news_search"],
      per_task_cap: "0.20",
      daily_cap: "2.00",
      approval_above: "0.05",
    },
  ],
};

export const sampleSteps: TourStep[] = [
  {
    index: 1,
    key: "everyday",
    title: "An everyday purchase",
    what_happens: "The agent buys a company record for 0.05 USDC.",
    why_it_matters: "Small purchases go through on their own, so the agent keeps working.",
    focus: "agents",
    your_turn: null,
  },
];
